name: 'Has label'
description: 'Checks if the current PR has label X, and outputs true/false, so that actions can be taken'
author: 'Stephan Grasmeijer'
inputs:
  token:
    description: 'Workflow token'
    required: true
    default: ''
  labels:
    description: 'Labels to check for, comma-separated'
    required: true
outputs:
  result:
    description: '"true" if there is a PR with one of the given labels, "false" if not'
runs:
  using: 'node12'
  main: 'dist/index.js'
