version: '3'
tasks:
  update:
    desc: Update deps and rebuild package
    cmds:
      - npm update
      - task: build
      - git add -A
      - 'git commit -m "chore: Upgrade deps"'
      - git push

  build:
    desc: Build package
    cmds:
      - npm run all
